version: '3'
services:
  django:
    build: &ref_0
      context: .
      dockerfile: compose/Dockerfile
    env_file: .env
    command: /gunicorn.sh
    ports:
      - '5000:5000'
    restart: always
  celeryworker:
    build: *ref_0
    env_file: .env
    command: /start-celeryworker.sh
    restart: always
  celerybeat:
    build: *ref_0
    env_file: .env
    command: /start-celerybeat.sh
    restart: always
  flower:
    build: *ref_0
    env_file: .env
    command: /start-flower.sh
    ports:
      - '5555:5555'
    restart: always
